# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wurfl_client}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guido Pinkas"]
  s.date = %q{2010-09-27}
  s.description = %q{WURFL Client is a library to do WURFL (http://wurfl.sourceforge.net/) mobile device detection for web applications. Included are tools to keep the WURFL file up to date automatically and to prepare a customized lookup tables, which allow a fast device detection.}
  s.email = %q{guido.pinkas@bindertrittenwein.com}
  s.executables = ["prepare_lookup.rb", "wurfl_minimize.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/prepare_lookup.rb",
     "bin/wurfl_minimize.rb",
     "lib/wurfl_client/device_profile.rb",
     "lib/wurfl_client/lookup_helper.rb",
     "lib/wurfl_client/lookup_preparer.rb",
     "lib/wurfl_client/ua_device_detector.rb",
     "lib/wurfl_client/wurfl_client.rb",
     "test/device_profile_test.rb",
     "wurfl_client.gemspec"
  ]
  s.homepage = %q{http://github.com/bluecat76/wurfl_client}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fast WURFL mobile device detection}
  s.test_files = [
    "test/lookup_helper_test.rb",
     "test/device_profile_test.rb",
     "test/wurfl_client_test.rb",
     "test/ua_device_detector_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<wurfl>, [">= 0"])
    else
      s.add_dependency(%q<wurfl>, [">= 0"])
    end
  else
    s.add_dependency(%q<wurfl>, [">= 0"])
  end
end

